// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	registry "github.com/michalgosek/workout-app-infrastrcutre/service-discovery/internal/registry"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// ListClusters provides a mock function with given fields:
func (_m *Repository) ListClusters() []registry.ServiceCluster {
	ret := _m.Called()

	var r0 []registry.ServiceCluster
	if rf, ok := ret.Get(0).(func() []registry.ServiceCluster); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]registry.ServiceCluster)
		}
	}

	return r0
}

// Repository_ListClusters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusters'
type Repository_ListClusters_Call struct {
	*mock.Call
}

// ListClusters is a helper method to define mock.On call
func (_e *Repository_Expecter) ListClusters() *Repository_ListClusters_Call {
	return &Repository_ListClusters_Call{Call: _e.mock.On("ListClusters")}
}

func (_c *Repository_ListClusters_Call) Run(run func()) *Repository_ListClusters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_ListClusters_Call) Return(_a0 []registry.ServiceCluster) *Repository_ListClusters_Call {
	_c.Call.Return(_a0)
	return _c
}

// QueryInstances provides a mock function with given fields: name
func (_m *Repository) QueryInstances(name string) ([]registry.ServiceInstance, error) {
	ret := _m.Called(name)

	var r0 []registry.ServiceInstance
	if rf, ok := ret.Get(0).(func(string) []registry.ServiceInstance); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]registry.ServiceInstance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_QueryInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryInstances'
type Repository_QueryInstances_Call struct {
	*mock.Call
}

// QueryInstances is a helper method to define mock.On call
//  - name string
func (_e *Repository_Expecter) QueryInstances(name interface{}) *Repository_QueryInstances_Call {
	return &Repository_QueryInstances_Call{Call: _e.mock.On("QueryInstances", name)}
}

func (_c *Repository_QueryInstances_Call) Run(run func(name string)) *Repository_QueryInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_QueryInstances_Call) Return(_a0 []registry.ServiceInstance, _a1 error) *Repository_QueryInstances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Register provides a mock function with given fields: ss
func (_m *Repository) Register(ss ...registry.ServiceInstance) error {
	_va := make([]interface{}, len(ss))
	for _i := range ss {
		_va[_i] = ss[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...registry.ServiceInstance) error); ok {
		r0 = rf(ss...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Repository_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//  - ss ...registry.ServiceInstance
func (_e *Repository_Expecter) Register(ss ...interface{}) *Repository_Register_Call {
	return &Repository_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{}, ss...)...)}
}

func (_c *Repository_Register_Call) Run(run func(ss ...registry.ServiceInstance)) *Repository_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]registry.ServiceInstance, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(registry.ServiceInstance)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Repository_Register_Call) Return(_a0 error) *Repository_Register_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateStatus provides a mock function with given fields: s
func (_m *Repository) UpdateStatus(s registry.ServiceInstance) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(registry.ServiceInstance) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type Repository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//  - s registry.ServiceInstance
func (_e *Repository_Expecter) UpdateStatus(s interface{}) *Repository_UpdateStatus_Call {
	return &Repository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", s)}
}

func (_c *Repository_UpdateStatus_Call) Run(run func(s registry.ServiceInstance)) *Repository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(registry.ServiceInstance))
	})
	return _c
}

func (_c *Repository_UpdateStatus_Call) Return(_a0 error) *Repository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}
