server:
  app:
    name: api-gateway
    addr: 8080
    shutdownTime: 5s 

endpoints:
  - method: GET
    location: localhost:8080 
    path: /api/trainings/user/calendar 
  - method: GET
    location: localhost:8080
    path: /api/trainings/trainer/calendar 


    
 

    