// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	command "github.com/michalgosek/workout-app-infrastrcutre/trainings-service/internal/application/command"

	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

type NotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *NotificationService) EXPECT() *NotificationService_Expecter {
	return &NotificationService_Expecter{mock: &_m.Mock}
}

// CreateNotification provides a mock function with given fields: ctx, n
func (_m *NotificationService) CreateNotification(ctx context.Context, n command.Notification) error {
	ret := _m.Called(ctx, n)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, command.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationService_CreateNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNotification'
type NotificationService_CreateNotification_Call struct {
	*mock.Call
}

// CreateNotification is a helper method to define mock.On call
//  - ctx context.Context
//  - n command.Notification
func (_e *NotificationService_Expecter) CreateNotification(ctx interface{}, n interface{}) *NotificationService_CreateNotification_Call {
	return &NotificationService_CreateNotification_Call{Call: _e.mock.On("CreateNotification", ctx, n)}
}

func (_c *NotificationService_CreateNotification_Call) Run(run func(ctx context.Context, n command.Notification)) *NotificationService_CreateNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(command.Notification))
	})
	return _c
}

func (_c *NotificationService_CreateNotification_Call) Return(_a0 error) *NotificationService_CreateNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewNotificationService interface {
	mock.TestingT
	Cleanup(func())
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNotificationService(t mockConstructorTestingTNewNotificationService) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
