// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/michalgosek/workout-app-infrastrcutre/trainings-service/internal/application/services"
	mock "github.com/stretchr/testify/mock"
)

// CustomerService is an autogenerated mock type for the CustomerService type
type CustomerService struct {
	mock.Mock
}

type CustomerService_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerService) EXPECT() *CustomerService_Expecter {
	return &CustomerService_Expecter{mock: &_m.Mock}
}

// CancelWorkoutDay provides a mock function with given fields: ctx, args
func (_m *CustomerService) CancelWorkoutDay(ctx context.Context, args services.CancelWorkoutDayArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.CancelWorkoutDayArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerService_CancelWorkoutDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelWorkoutDay'
type CustomerService_CancelWorkoutDay_Call struct {
	*mock.Call
}

// CancelWorkoutDay is a helper method to define mock.On call
//  - ctx context.Context
//  - args services.CancelWorkoutDayArgs
func (_e *CustomerService_Expecter) CancelWorkoutDay(ctx interface{}, args interface{}) *CustomerService_CancelWorkoutDay_Call {
	return &CustomerService_CancelWorkoutDay_Call{Call: _e.mock.On("CancelWorkoutDay", ctx, args)}
}

func (_c *CustomerService_CancelWorkoutDay_Call) Run(run func(ctx context.Context, args services.CancelWorkoutDayArgs)) *CustomerService_CancelWorkoutDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.CancelWorkoutDayArgs))
	})
	return _c
}

func (_c *CustomerService_CancelWorkoutDay_Call) Return(_a0 error) *CustomerService_CancelWorkoutDay_Call {
	_c.Call.Return(_a0)
	return _c
}

// ScheduleWorkoutDay provides a mock function with given fields: ctx, args
func (_m *CustomerService) ScheduleWorkoutDay(ctx context.Context, args services.ScheduleWorkoutDayArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ScheduleWorkoutDayArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CustomerService_ScheduleWorkoutDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleWorkoutDay'
type CustomerService_ScheduleWorkoutDay_Call struct {
	*mock.Call
}

// ScheduleWorkoutDay is a helper method to define mock.On call
//  - ctx context.Context
//  - args services.ScheduleWorkoutDayArgs
func (_e *CustomerService_Expecter) ScheduleWorkoutDay(ctx interface{}, args interface{}) *CustomerService_ScheduleWorkoutDay_Call {
	return &CustomerService_ScheduleWorkoutDay_Call{Call: _e.mock.On("ScheduleWorkoutDay", ctx, args)}
}

func (_c *CustomerService_ScheduleWorkoutDay_Call) Run(run func(ctx context.Context, args services.ScheduleWorkoutDayArgs)) *CustomerService_ScheduleWorkoutDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.ScheduleWorkoutDayArgs))
	})
	return _c
}

func (_c *CustomerService_ScheduleWorkoutDay_Call) Return(_a0 error) *CustomerService_ScheduleWorkoutDay_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewCustomerService interface {
	mock.TestingT
	Cleanup(func())
}

// NewCustomerService creates a new instance of CustomerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCustomerService(t mockConstructorTestingTNewCustomerService) *CustomerService {
	mock := &CustomerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
