// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	trainings "github.com/michalgosek/workout-app-infrastrcutre/trainings-service/internal/application/services/trainings"
	mock "github.com/stretchr/testify/mock"
)

// TrainingsService is an autogenerated mock type for the TrainingsService type
type TrainingsService struct {
	mock.Mock
}

type TrainingsService_Expecter struct {
	mock *mock.Mock
}

func (_m *TrainingsService) EXPECT() *TrainingsService_Expecter {
	return &TrainingsService_Expecter{mock: &_m.Mock}
}

// AssignCustomerToWorkoutGroup provides a mock function with given fields: ctx, args
func (_m *TrainingsService) AssignCustomerToWorkoutGroup(ctx context.Context, args trainings.AssignCustomerToWorkoutArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, trainings.AssignCustomerToWorkoutArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrainingsService_AssignCustomerToWorkoutGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignCustomerToWorkoutGroup'
type TrainingsService_AssignCustomerToWorkoutGroup_Call struct {
	*mock.Call
}

// AssignCustomerToWorkoutGroup is a helper method to define mock.On call
//  - ctx context.Context
//  - args trainings.AssignCustomerToWorkoutArgs
func (_e *TrainingsService_Expecter) AssignCustomerToWorkoutGroup(ctx interface{}, args interface{}) *TrainingsService_AssignCustomerToWorkoutGroup_Call {
	return &TrainingsService_AssignCustomerToWorkoutGroup_Call{Call: _e.mock.On("AssignCustomerToWorkoutGroup", ctx, args)}
}

func (_c *TrainingsService_AssignCustomerToWorkoutGroup_Call) Run(run func(ctx context.Context, args trainings.AssignCustomerToWorkoutArgs)) *TrainingsService_AssignCustomerToWorkoutGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(trainings.AssignCustomerToWorkoutArgs))
	})
	return _c
}

func (_c *TrainingsService_AssignCustomerToWorkoutGroup_Call) Return(_a0 error) *TrainingsService_AssignCustomerToWorkoutGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

// CancelCustomerWorkout provides a mock function with given fields: ctx, args
func (_m *TrainingsService) CancelCustomerWorkout(ctx context.Context, args trainings.CancelCustomerWorkoutArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, trainings.CancelCustomerWorkoutArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrainingsService_CancelCustomerWorkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelCustomerWorkout'
type TrainingsService_CancelCustomerWorkout_Call struct {
	*mock.Call
}

// CancelCustomerWorkout is a helper method to define mock.On call
//  - ctx context.Context
//  - args trainings.CancelCustomerWorkoutArgs
func (_e *TrainingsService_Expecter) CancelCustomerWorkout(ctx interface{}, args interface{}) *TrainingsService_CancelCustomerWorkout_Call {
	return &TrainingsService_CancelCustomerWorkout_Call{Call: _e.mock.On("CancelCustomerWorkout", ctx, args)}
}

func (_c *TrainingsService_CancelCustomerWorkout_Call) Run(run func(ctx context.Context, args trainings.CancelCustomerWorkoutArgs)) *TrainingsService_CancelCustomerWorkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(trainings.CancelCustomerWorkoutArgs))
	})
	return _c
}

func (_c *TrainingsService_CancelCustomerWorkout_Call) Return(_a0 error) *TrainingsService_CancelCustomerWorkout_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewTrainingsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTrainingsService creates a new instance of TrainingsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTrainingsService(t mockConstructorTestingTNewTrainingsService) *TrainingsService {
	mock := &TrainingsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
