// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CancelWorkoutsHandlerRepository is an autogenerated mock type for the CancelWorkoutsHandlerRepository type
type CancelWorkoutsHandlerRepository struct {
	mock.Mock
}

type CancelWorkoutsHandlerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CancelWorkoutsHandlerRepository) EXPECT() *CancelWorkoutsHandlerRepository_Expecter {
	return &CancelWorkoutsHandlerRepository_Expecter{mock: &_m.Mock}
}

// DeleteWorkoutGroups provides a mock function with given fields: ctx, trainerUUID
func (_m *CancelWorkoutsHandlerRepository) DeleteWorkoutGroups(ctx context.Context, trainerUUID string) error {
	ret := _m.Called(ctx, trainerUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, trainerUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelWorkoutsHandlerRepository_DeleteWorkoutGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkoutGroups'
type CancelWorkoutsHandlerRepository_DeleteWorkoutGroups_Call struct {
	*mock.Call
}

// DeleteWorkoutGroups is a helper method to define mock.On call
//  - ctx context.Context
//  - trainerUUID string
func (_e *CancelWorkoutsHandlerRepository_Expecter) DeleteWorkoutGroups(ctx interface{}, trainerUUID interface{}) *CancelWorkoutsHandlerRepository_DeleteWorkoutGroups_Call {
	return &CancelWorkoutsHandlerRepository_DeleteWorkoutGroups_Call{Call: _e.mock.On("DeleteWorkoutGroups", ctx, trainerUUID)}
}

func (_c *CancelWorkoutsHandlerRepository_DeleteWorkoutGroups_Call) Run(run func(ctx context.Context, trainerUUID string)) *CancelWorkoutsHandlerRepository_DeleteWorkoutGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CancelWorkoutsHandlerRepository_DeleteWorkoutGroups_Call) Return(_a0 error) *CancelWorkoutsHandlerRepository_DeleteWorkoutGroups_Call {
	_c.Call.Return(_a0)
	return _c
}
