// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	trainer "github.com/michalgosek/workout-app-infrastrcutre/trainings-service/internal/application/services/trainer"
	mock "github.com/stretchr/testify/mock"
)

// TrainerService is an autogenerated mock type for the TrainerService type
type TrainerService struct {
	mock.Mock
}

type TrainerService_Expecter struct {
	mock *mock.Mock
}

func (_m *TrainerService) EXPECT() *TrainerService_Expecter {
	return &TrainerService_Expecter{mock: &_m.Mock}
}

// CreateWorkoutGroup provides a mock function with given fields: ctx, args
func (_m *TrainerService) CreateWorkoutGroup(ctx context.Context, args trainer.CreateWorkoutGroupArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, trainer.CreateWorkoutGroupArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrainerService_CreateWorkoutGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkoutGroup'
type TrainerService_CreateWorkoutGroup_Call struct {
	*mock.Call
}

// CreateWorkoutGroup is a helper method to define mock.On call
//  - ctx context.Context
//  - args trainer.CreateWorkoutGroupArgs
func (_e *TrainerService_Expecter) CreateWorkoutGroup(ctx interface{}, args interface{}) *TrainerService_CreateWorkoutGroup_Call {
	return &TrainerService_CreateWorkoutGroup_Call{Call: _e.mock.On("CreateWorkoutGroup", ctx, args)}
}

func (_c *TrainerService_CreateWorkoutGroup_Call) Run(run func(ctx context.Context, args trainer.CreateWorkoutGroupArgs)) *TrainerService_CreateWorkoutGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(trainer.CreateWorkoutGroupArgs))
	})
	return _c
}

func (_c *TrainerService_CreateWorkoutGroup_Call) Return(_a0 error) *TrainerService_CreateWorkoutGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewTrainerService interface {
	mock.TestingT
	Cleanup(func())
}

// NewTrainerService creates a new instance of TrainerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTrainerService(t mockConstructorTestingTNewTrainerService) *TrainerService {
	mock := &TrainerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
