// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CustomerRepository is an autogenerated mock type for the CustomerRepository type
type CustomerRepository struct {
	mock.Mock
}

type CustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerRepository) EXPECT() *CustomerRepository_Expecter {
	return &CustomerRepository_Expecter{mock: &_m.Mock}
}
