// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	trainer "github.com/michalgosek/workout-app-infrastrcutre/trainings-service/internal/domain/trainer"
	mock "github.com/stretchr/testify/mock"
)

// TrainerQueries is an autogenerated mock type for the TrainerQueries type
type TrainerQueries struct {
	mock.Mock
}

type TrainerQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *TrainerQueries) EXPECT() *TrainerQueries_Expecter {
	return &TrainerQueries_Expecter{mock: &_m.Mock}
}

// QueryWorkoutGroup provides a mock function with given fields: ctx, groupUUID
func (_m *TrainerQueries) QueryWorkoutGroup(ctx context.Context, groupUUID string) (trainer.WorkoutGroup, error) {
	ret := _m.Called(ctx, groupUUID)

	var r0 trainer.WorkoutGroup
	if rf, ok := ret.Get(0).(func(context.Context, string) trainer.WorkoutGroup); ok {
		r0 = rf(ctx, groupUUID)
	} else {
		r0 = ret.Get(0).(trainer.WorkoutGroup)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, groupUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrainerQueries_QueryWorkoutGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryWorkoutGroup'
type TrainerQueries_QueryWorkoutGroup_Call struct {
	*mock.Call
}

// QueryWorkoutGroup is a helper method to define mock.On call
//  - ctx context.Context
//  - groupUUID string
func (_e *TrainerQueries_Expecter) QueryWorkoutGroup(ctx interface{}, groupUUID interface{}) *TrainerQueries_QueryWorkoutGroup_Call {
	return &TrainerQueries_QueryWorkoutGroup_Call{Call: _e.mock.On("QueryWorkoutGroup", ctx, groupUUID)}
}

func (_c *TrainerQueries_QueryWorkoutGroup_Call) Run(run func(ctx context.Context, groupUUID string)) *TrainerQueries_QueryWorkoutGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TrainerQueries_QueryWorkoutGroup_Call) Return(_a0 trainer.WorkoutGroup, _a1 error) *TrainerQueries_QueryWorkoutGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// QueryWorkoutGroups provides a mock function with given fields: ctx, trainerUUID
func (_m *TrainerQueries) QueryWorkoutGroups(ctx context.Context, trainerUUID string) ([]trainer.WorkoutGroup, error) {
	ret := _m.Called(ctx, trainerUUID)

	var r0 []trainer.WorkoutGroup
	if rf, ok := ret.Get(0).(func(context.Context, string) []trainer.WorkoutGroup); ok {
		r0 = rf(ctx, trainerUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trainer.WorkoutGroup)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trainerUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrainerQueries_QueryWorkoutGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryWorkoutGroups'
type TrainerQueries_QueryWorkoutGroups_Call struct {
	*mock.Call
}

// QueryWorkoutGroups is a helper method to define mock.On call
//  - ctx context.Context
//  - trainerUUID string
func (_e *TrainerQueries_Expecter) QueryWorkoutGroups(ctx interface{}, trainerUUID interface{}) *TrainerQueries_QueryWorkoutGroups_Call {
	return &TrainerQueries_QueryWorkoutGroups_Call{Call: _e.mock.On("QueryWorkoutGroups", ctx, trainerUUID)}
}

func (_c *TrainerQueries_QueryWorkoutGroups_Call) Run(run func(ctx context.Context, trainerUUID string)) *TrainerQueries_QueryWorkoutGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TrainerQueries_QueryWorkoutGroups_Call) Return(_a0 []trainer.WorkoutGroup, _a1 error) *TrainerQueries_QueryWorkoutGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
