// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	trainer "github.com/michalgosek/workout-app-infrastrcutre/trainings-service/internal/domain/trainer"
	mock "github.com/stretchr/testify/mock"
)

// TrainerRepository is an autogenerated mock type for the TrainerRepository type
type TrainerRepository struct {
	mock.Mock
}

type TrainerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TrainerRepository) EXPECT() *TrainerRepository_Expecter {
	return &TrainerRepository_Expecter{mock: &_m.Mock}
}

// DeleteWorkoutGroup provides a mock function with given fields: ctx, UUID, trainerUUID
func (_m *TrainerRepository) DeleteWorkoutGroup(ctx context.Context, UUID string, trainerUUID string) error {
	ret := _m.Called(ctx, UUID, trainerUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, UUID, trainerUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrainerRepository_DeleteWorkoutGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkoutGroup'
type TrainerRepository_DeleteWorkoutGroup_Call struct {
	*mock.Call
}

// DeleteWorkoutGroup is a helper method to define mock.On call
//  - ctx context.Context
//  - UUID string
//  - trainerUUID string
func (_e *TrainerRepository_Expecter) DeleteWorkoutGroup(ctx interface{}, UUID interface{}, trainerUUID interface{}) *TrainerRepository_DeleteWorkoutGroup_Call {
	return &TrainerRepository_DeleteWorkoutGroup_Call{Call: _e.mock.On("DeleteWorkoutGroup", ctx, UUID, trainerUUID)}
}

func (_c *TrainerRepository_DeleteWorkoutGroup_Call) Run(run func(ctx context.Context, UUID string, trainerUUID string)) *TrainerRepository_DeleteWorkoutGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TrainerRepository_DeleteWorkoutGroup_Call) Return(_a0 error) *TrainerRepository_DeleteWorkoutGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

// DeleteWorkoutGroups provides a mock function with given fields: ctx, trainerUUID
func (_m *TrainerRepository) DeleteWorkoutGroups(ctx context.Context, trainerUUID string) error {
	ret := _m.Called(ctx, trainerUUID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, trainerUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrainerRepository_DeleteWorkoutGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkoutGroups'
type TrainerRepository_DeleteWorkoutGroups_Call struct {
	*mock.Call
}

// DeleteWorkoutGroups is a helper method to define mock.On call
//  - ctx context.Context
//  - trainerUUID string
func (_e *TrainerRepository_Expecter) DeleteWorkoutGroups(ctx interface{}, trainerUUID interface{}) *TrainerRepository_DeleteWorkoutGroups_Call {
	return &TrainerRepository_DeleteWorkoutGroups_Call{Call: _e.mock.On("DeleteWorkoutGroups", ctx, trainerUUID)}
}

func (_c *TrainerRepository_DeleteWorkoutGroups_Call) Run(run func(ctx context.Context, trainerUUID string)) *TrainerRepository_DeleteWorkoutGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TrainerRepository_DeleteWorkoutGroups_Call) Return(_a0 error) *TrainerRepository_DeleteWorkoutGroups_Call {
	_c.Call.Return(_a0)
	return _c
}

// QueryWorkoutGroup provides a mock function with given fields: ctx, UUID, trainerUUID
func (_m *TrainerRepository) QueryWorkoutGroup(ctx context.Context, UUID string, trainerUUID string) (trainer.WorkoutGroup, error) {
	ret := _m.Called(ctx, UUID, trainerUUID)

	var r0 trainer.WorkoutGroup
	if rf, ok := ret.Get(0).(func(context.Context, string, string) trainer.WorkoutGroup); ok {
		r0 = rf(ctx, UUID, trainerUUID)
	} else {
		r0 = ret.Get(0).(trainer.WorkoutGroup)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, UUID, trainerUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrainerRepository_QueryWorkoutGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryWorkoutGroup'
type TrainerRepository_QueryWorkoutGroup_Call struct {
	*mock.Call
}

// QueryWorkoutGroup is a helper method to define mock.On call
//  - ctx context.Context
//  - UUID string
//  - trainerUUID string
func (_e *TrainerRepository_Expecter) QueryWorkoutGroup(ctx interface{}, UUID interface{}, trainerUUID interface{}) *TrainerRepository_QueryWorkoutGroup_Call {
	return &TrainerRepository_QueryWorkoutGroup_Call{Call: _e.mock.On("QueryWorkoutGroup", ctx, UUID, trainerUUID)}
}

func (_c *TrainerRepository_QueryWorkoutGroup_Call) Run(run func(ctx context.Context, UUID string, trainerUUID string)) *TrainerRepository_QueryWorkoutGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TrainerRepository_QueryWorkoutGroup_Call) Return(_a0 trainer.WorkoutGroup, _a1 error) *TrainerRepository_QueryWorkoutGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// QueryWorkoutGroups provides a mock function with given fields: ctx, trainerUUID
func (_m *TrainerRepository) QueryWorkoutGroups(ctx context.Context, trainerUUID string) ([]trainer.WorkoutGroup, error) {
	ret := _m.Called(ctx, trainerUUID)

	var r0 []trainer.WorkoutGroup
	if rf, ok := ret.Get(0).(func(context.Context, string) []trainer.WorkoutGroup); ok {
		r0 = rf(ctx, trainerUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]trainer.WorkoutGroup)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, trainerUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TrainerRepository_QueryWorkoutGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryWorkoutGroups'
type TrainerRepository_QueryWorkoutGroups_Call struct {
	*mock.Call
}

// QueryWorkoutGroups is a helper method to define mock.On call
//  - ctx context.Context
//  - trainerUUID string
func (_e *TrainerRepository_Expecter) QueryWorkoutGroups(ctx interface{}, trainerUUID interface{}) *TrainerRepository_QueryWorkoutGroups_Call {
	return &TrainerRepository_QueryWorkoutGroups_Call{Call: _e.mock.On("QueryWorkoutGroups", ctx, trainerUUID)}
}

func (_c *TrainerRepository_QueryWorkoutGroups_Call) Run(run func(ctx context.Context, trainerUUID string)) *TrainerRepository_QueryWorkoutGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TrainerRepository_QueryWorkoutGroups_Call) Return(_a0 []trainer.WorkoutGroup, _a1 error) *TrainerRepository_QueryWorkoutGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpsertWorkoutGroup provides a mock function with given fields: ctx, schedule
func (_m *TrainerRepository) UpsertWorkoutGroup(ctx context.Context, schedule trainer.WorkoutGroup) error {
	ret := _m.Called(ctx, schedule)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, trainer.WorkoutGroup) error); ok {
		r0 = rf(ctx, schedule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TrainerRepository_UpsertWorkoutGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertWorkoutGroup'
type TrainerRepository_UpsertWorkoutGroup_Call struct {
	*mock.Call
}

// UpsertWorkoutGroup is a helper method to define mock.On call
//  - ctx context.Context
//  - schedule trainer.WorkoutGroup
func (_e *TrainerRepository_Expecter) UpsertWorkoutGroup(ctx interface{}, schedule interface{}) *TrainerRepository_UpsertWorkoutGroup_Call {
	return &TrainerRepository_UpsertWorkoutGroup_Call{Call: _e.mock.On("UpsertWorkoutGroup", ctx, schedule)}
}

func (_c *TrainerRepository_UpsertWorkoutGroup_Call) Run(run func(ctx context.Context, schedule trainer.WorkoutGroup)) *TrainerRepository_UpsertWorkoutGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(trainer.WorkoutGroup))
	})
	return _c
}

func (_c *TrainerRepository_UpsertWorkoutGroup_Call) Return(_a0 error) *TrainerRepository_UpsertWorkoutGroup_Call {
	_c.Call.Return(_a0)
	return _c
}
